language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements/test.txt
script:
  - flake8 --ignore=E501 .
  - coverage run --source='.' runtests.py
after_success:
  - coveralls
notifications:
  - recipients:
    - thibault@miximum.fr
  - on_success: change
  - on_failure: always
